//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BuyingPartner"/>
 *         &lt;element ref="{}OriginatingPartner"/>
 *         &lt;element ref="{}SellingPartner"/>
 *         &lt;element ref="{}Shipment"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "buyingPartner",
    "originatingPartner",
    "sellingPartner",
    "shipment"
})
@XmlRootElement(name = "AdvancedShipmentNotification")
public class AdvancedShipmentNotification {

    @XmlElement(name = "BuyingPartner", required = true)
    protected BuyingPartner buyingPartner;
    @XmlElement(name = "OriginatingPartner", required = true)
    protected OriginatingPartner originatingPartner;
    @XmlElement(name = "SellingPartner", required = true)
    protected SellingPartner sellingPartner;
    @XmlElement(name = "Shipment", required = true)
    protected Shipment shipment;

    /**
     * Gets the value of the buyingPartner property.
     * 
     * @return
     *     possible object is
     *     {@link BuyingPartner }
     *     
     */
    public BuyingPartner getBuyingPartner() {
        return buyingPartner;
    }

    /**
     * Sets the value of the buyingPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyingPartner }
     *     
     */
    public void setBuyingPartner(BuyingPartner value) {
        this.buyingPartner = value;
    }

    /**
     * Gets the value of the originatingPartner property.
     * 
     * @return
     *     possible object is
     *     {@link OriginatingPartner }
     *     
     */
    public OriginatingPartner getOriginatingPartner() {
        return originatingPartner;
    }

    /**
     * Sets the value of the originatingPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginatingPartner }
     *     
     */
    public void setOriginatingPartner(OriginatingPartner value) {
        this.originatingPartner = value;
    }

    /**
     * Gets the value of the sellingPartner property.
     * 
     * @return
     *     possible object is
     *     {@link SellingPartner }
     *     
     */
    public SellingPartner getSellingPartner() {
        return sellingPartner;
    }

    /**
     * Sets the value of the sellingPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellingPartner }
     *     
     */
    public void setSellingPartner(SellingPartner value) {
        this.sellingPartner = value;
    }

    /**
     * Gets the value of the shipment property.
     * 
     * @return
     *     possible object is
     *     {@link Shipment }
     *     
     */
    public Shipment getShipment() {
        return shipment;
    }

    /**
     * Sets the value of the shipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipment }
     *     
     */
    public void setShipment(Shipment value) {
        this.shipment = value;
    }

}
