//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GlobalDocumentReferenceTypeCode"/>
 *         &lt;element ref="{}LineNumber" minOccurs="0"/>
 *         &lt;element ref="{}LotShipReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ProprietaryDocumentIdentifier"/>
 *         &lt;element ref="{}requestedQuantity" minOccurs="0"/>
 *         &lt;element ref="{}shippedLotQuantity"/>
 *         &lt;element ref="{}subLineNumber" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalDocumentReferenceTypeCode",
    "lineNumber",
    "lotShipReference",
    "proprietaryDocumentIdentifier",
    "requestedQuantity",
    "shippedLotQuantity",
    "subLineNumber"
})
@XmlRootElement(name = "DocumentSubLineLotShipReference")
public class DocumentSubLineLotShipReference {

    @XmlElement(name = "GlobalDocumentReferenceTypeCode", required = true)
    protected String globalDocumentReferenceTypeCode;
    @XmlElement(name = "LineNumber")
    protected String lineNumber;
    @XmlElement(name = "LotShipReference")
    protected List<LotShipReference> lotShipReference;
    @XmlElement(name = "ProprietaryDocumentIdentifier", required = true)
    protected String proprietaryDocumentIdentifier;
    protected RequestedQuantity requestedQuantity;
    @XmlElement(required = true)
    protected ShippedLotQuantity shippedLotQuantity;
    protected SubLineNumber subLineNumber;

    /**
     * Gets the value of the globalDocumentReferenceTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalDocumentReferenceTypeCode() {
        return globalDocumentReferenceTypeCode;
    }

    /**
     * Sets the value of the globalDocumentReferenceTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalDocumentReferenceTypeCode(String value) {
        this.globalDocumentReferenceTypeCode = value;
    }

    /**
     * Gets the value of the lineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineNumber(String value) {
        this.lineNumber = value;
    }

    /**
     * Gets the value of the lotShipReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lotShipReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLotShipReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LotShipReference }
     * 
     * 
     */
    public List<LotShipReference> getLotShipReference() {
        if (lotShipReference == null) {
            lotShipReference = new ArrayList<LotShipReference>();
        }
        return this.lotShipReference;
    }

    /**
     * Gets the value of the proprietaryDocumentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProprietaryDocumentIdentifier() {
        return proprietaryDocumentIdentifier;
    }

    /**
     * Sets the value of the proprietaryDocumentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProprietaryDocumentIdentifier(String value) {
        this.proprietaryDocumentIdentifier = value;
    }

    /**
     * Gets the value of the requestedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedQuantity }
     *     
     */
    public RequestedQuantity getRequestedQuantity() {
        return requestedQuantity;
    }

    /**
     * Sets the value of the requestedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedQuantity }
     *     
     */
    public void setRequestedQuantity(RequestedQuantity value) {
        this.requestedQuantity = value;
    }

    /**
     * Gets the value of the shippedLotQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link ShippedLotQuantity }
     *     
     */
    public ShippedLotQuantity getShippedLotQuantity() {
        return shippedLotQuantity;
    }

    /**
     * Sets the value of the shippedLotQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippedLotQuantity }
     *     
     */
    public void setShippedLotQuantity(ShippedLotQuantity value) {
        this.shippedLotQuantity = value;
    }

    /**
     * Gets the value of the subLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SubLineNumber }
     *     
     */
    public SubLineNumber getSubLineNumber() {
        return subLineNumber;
    }

    /**
     * Sets the value of the subLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubLineNumber }
     *     
     */
    public void setSubLineNumber(SubLineNumber value) {
        this.subLineNumber = value;
    }

}
