//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GlobalPhysicalUnitOfMeasureCode"/>
 *         &lt;element ref="{}HeightDimension" minOccurs="0"/>
 *         &lt;element ref="{}LengthDimension" minOccurs="0"/>
 *         &lt;element ref="{}WidthDimension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalPhysicalUnitOfMeasureCode",
    "heightDimension",
    "lengthDimension",
    "widthDimension"
})
@XmlRootElement(name = "LinearPhysicalDimension")
public class LinearPhysicalDimension {

    @XmlElement(name = "GlobalPhysicalUnitOfMeasureCode", required = true)
    protected String globalPhysicalUnitOfMeasureCode;
    @XmlElement(name = "HeightDimension")
    protected String heightDimension;
    @XmlElement(name = "LengthDimension")
    protected String lengthDimension;
    @XmlElement(name = "WidthDimension")
    protected String widthDimension;

    /**
     * Gets the value of the globalPhysicalUnitOfMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalPhysicalUnitOfMeasureCode() {
        return globalPhysicalUnitOfMeasureCode;
    }

    /**
     * Sets the value of the globalPhysicalUnitOfMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalPhysicalUnitOfMeasureCode(String value) {
        this.globalPhysicalUnitOfMeasureCode = value;
    }

    /**
     * Gets the value of the heightDimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeightDimension() {
        return heightDimension;
    }

    /**
     * Sets the value of the heightDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeightDimension(String value) {
        this.heightDimension = value;
    }

    /**
     * Gets the value of the lengthDimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthDimension() {
        return lengthDimension;
    }

    /**
     * Sets the value of the lengthDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthDimension(String value) {
        this.lengthDimension = value;
    }

    /**
     * Gets the value of the widthDimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthDimension() {
        return widthDimension;
    }

    /**
     * Sets the value of the widthDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthDimension(String value) {
        this.widthDimension = value;
    }

}
