//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}primaryLotIdentifier"/>
 *         &lt;element ref="{}secondaryLotIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primaryLotIdentifier",
    "secondaryLotIdentifier"
})
@XmlRootElement(name = "LotIdentification")
public class LotIdentification {

    @XmlElement(required = true)
    protected PrimaryLotIdentifier primaryLotIdentifier;
    protected SecondaryLotIdentifier secondaryLotIdentifier;

    /**
     * Gets the value of the primaryLotIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryLotIdentifier }
     *     
     */
    public PrimaryLotIdentifier getPrimaryLotIdentifier() {
        return primaryLotIdentifier;
    }

    /**
     * Sets the value of the primaryLotIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryLotIdentifier }
     *     
     */
    public void setPrimaryLotIdentifier(PrimaryLotIdentifier value) {
        this.primaryLotIdentifier = value;
    }

    /**
     * Gets the value of the secondaryLotIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SecondaryLotIdentifier }
     *     
     */
    public SecondaryLotIdentifier getSecondaryLotIdentifier() {
        return secondaryLotIdentifier;
    }

    /**
     * Sets the value of the secondaryLotIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecondaryLotIdentifier }
     *     
     */
    public void setSecondaryLotIdentifier(SecondaryLotIdentifier value) {
        this.secondaryLotIdentifier = value;
    }

}
