//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GlobalLotQuantityClassificationCode"/>
 *         &lt;element ref="{}GlobalProductUnitOfMeasureCode"/>
 *         &lt;element ref="{}ProductQuantity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalLotQuantityClassificationCode",
    "globalProductUnitOfMeasureCode",
    "productQuantity"
})
@XmlRootElement(name = "LotQuantity")
public class LotQuantity {

    @XmlElement(name = "GlobalLotQuantityClassificationCode", required = true)
    protected String globalLotQuantityClassificationCode;
    @XmlElement(name = "GlobalProductUnitOfMeasureCode", required = true)
    protected String globalProductUnitOfMeasureCode;
    @XmlElement(name = "ProductQuantity", required = true)
    protected String productQuantity;

    /**
     * Gets the value of the globalLotQuantityClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalLotQuantityClassificationCode() {
        return globalLotQuantityClassificationCode;
    }

    /**
     * Sets the value of the globalLotQuantityClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalLotQuantityClassificationCode(String value) {
        this.globalLotQuantityClassificationCode = value;
    }

    /**
     * Gets the value of the globalProductUnitOfMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalProductUnitOfMeasureCode() {
        return globalProductUnitOfMeasureCode;
    }

    /**
     * Sets the value of the globalProductUnitOfMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalProductUnitOfMeasureCode(String value) {
        this.globalProductUnitOfMeasureCode = value;
    }

    /**
     * Gets the value of the productQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductQuantity() {
        return productQuantity;
    }

    /**
     * Sets the value of the productQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductQuantity(String value) {
        this.productQuantity = value;
    }

}
