//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}countryOfOrigin" minOccurs="0"/>
 *         &lt;element ref="{}manufactureDate" minOccurs="0"/>
 *         &lt;element ref="{}productSerialIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countryOfOrigin",
    "manufactureDate",
    "productSerialIdentifier"
})
@XmlRootElement(name = "ManufacturerProfile")
public class ManufacturerProfile {

    protected CountryOfOrigin countryOfOrigin;
    protected ManufactureDate manufactureDate;
    protected ProductSerialIdentifier productSerialIdentifier;

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link CountryOfOrigin }
     *     
     */
    public CountryOfOrigin getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryOfOrigin }
     *     
     */
    public void setCountryOfOrigin(CountryOfOrigin value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the manufactureDate property.
     * 
     * @return
     *     possible object is
     *     {@link ManufactureDate }
     *     
     */
    public ManufactureDate getManufactureDate() {
        return manufactureDate;
    }

    /**
     * Sets the value of the manufactureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufactureDate }
     *     
     */
    public void setManufactureDate(ManufactureDate value) {
        this.manufactureDate = value;
    }

    /**
     * Gets the value of the productSerialIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSerialIdentifier }
     *     
     */
    public ProductSerialIdentifier getProductSerialIdentifier() {
        return productSerialIdentifier;
    }

    /**
     * Sets the value of the productSerialIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSerialIdentifier }
     *     
     */
    public void setProductSerialIdentifier(ProductSerialIdentifier value) {
        this.productSerialIdentifier = value;
    }

}
