//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.e2open.transform package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProductQuantity_QNAME = new QName("", "ProductQuantity");
    private final static QName _NationalHarmonizedTariffScheduleCode_QNAME = new QName("", "NationalHarmonizedTariffScheduleCode");
    private final static QName _GlobalTrackingReferenceTypeCode_QNAME = new QName("", "GlobalTrackingReferenceTypeCode");
    private final static QName _ProprietaryBusinessIdentifier_QNAME = new QName("", "ProprietaryBusinessIdentifier");
    private final static QName _WidthDimension_QNAME = new QName("", "WidthDimension");
    private final static QName _GlobalCountryCode_QNAME = new QName("", "GlobalCountryCode");
    private final static QName _ProprietaryReferenceIdentifier_QNAME = new QName("", "ProprietaryReferenceIdentifier");
    private final static QName _ProprietaryDocumentIdentifier_QNAME = new QName("", "ProprietaryDocumentIdentifier");
    private final static QName _LengthDimension_QNAME = new QName("", "LengthDimension");
    private final static QName _LineNumber_QNAME = new QName("", "LineNumber");
    private final static QName _CommunicationsNumber_QNAME = new QName("", "CommunicationsNumber");
    private final static QName _ProprietarySerialIdentifier_QNAME = new QName("", "ProprietarySerialIdentifier");
    private final static QName _ProprietaryLotIdentifier_QNAME = new QName("", "ProprietaryLotIdentifier");
    private final static QName _ProprietaryDomainIdentifier_QNAME = new QName("", "ProprietaryDomainIdentifier");
    private final static QName _NationalPostalCode_QNAME = new QName("", "NationalPostalCode");
    private final static QName _GlobalLotQuantityClassificationCode_QNAME = new QName("", "GlobalLotQuantityClassificationCode");
    private final static QName _GlobalBusinessIdentifier_QNAME = new QName("", "GlobalBusinessIdentifier");
    private final static QName _GlobalShippingServiceLevelCode_QNAME = new QName("", "GlobalShippingServiceLevelCode");
    private final static QName _HeightDimension_QNAME = new QName("", "HeightDimension");
    private final static QName _GlobalPartnerClassificationCode_QNAME = new QName("", "GlobalPartnerClassificationCode");
    private final static QName _GlobalSupplyChainCode_QNAME = new QName("", "GlobalSupplyChainCode");
    private final static QName _GlobalShipDateCode_QNAME = new QName("", "GlobalShipDateCode");
    private final static QName _GlobalProductIdentifier_QNAME = new QName("", "GlobalProductIdentifier");
    private final static QName _GlobalDocumentReferenceTypeCode_QNAME = new QName("", "GlobalDocumentReferenceTypeCode");
    private final static QName _ProprietaryIdentifierAuthority_QNAME = new QName("", "ProprietaryIdentifierAuthority");
    private final static QName _GlobalPartnerRoleClassificationCode_QNAME = new QName("", "GlobalPartnerRoleClassificationCode");
    private final static QName _GlobalLocationIdentifier_QNAME = new QName("", "GlobalLocationIdentifier");
    private final static QName _GlobalShipmentChangeDispositionCode_QNAME = new QName("", "GlobalShipmentChangeDispositionCode");
    private final static QName _GlobalPhysicalUnitOfMeasureCode_QNAME = new QName("", "GlobalPhysicalUnitOfMeasureCode");
    private final static QName _NationalExportControlClassificationCode_QNAME = new QName("", "NationalExportControlClassificationCode");
    private final static QName _GlobalPackageTypeCode_QNAME = new QName("", "GlobalPackageTypeCode");
    private final static QName _DateStamp_QNAME = new QName("", "DateStamp");
    private final static QName _GlobalCarrierCode_QNAME = new QName("", "GlobalCarrierCode");
    private final static QName _CountableAmount_QNAME = new QName("", "CountableAmount");
    private final static QName _ProprietaryShipmentTrackingIdentifier_QNAME = new QName("", "ProprietaryShipmentTrackingIdentifier");
    private final static QName _EmailAddress_QNAME = new QName("", "EmailAddress");
    private final static QName _GlobalIncotermsCode_QNAME = new QName("", "GlobalIncotermsCode");
    private final static QName _AccountNumber_QNAME = new QName("", "AccountNumber");
    private final static QName _Mass_QNAME = new QName("", "Mass");
    private final static QName _ProprietaryProductIdentifier_QNAME = new QName("", "ProprietaryProductIdentifier");
    private final static QName _GlobalShipmentModeCode_QNAME = new QName("", "GlobalShipmentModeCode");
    private final static QName _GlobalDocumentFunctionCode_QNAME = new QName("", "GlobalDocumentFunctionCode");
    private final static QName _GlobalProductUnitOfMeasureCode_QNAME = new QName("", "GlobalProductUnitOfMeasureCode");
    private final static QName _NationalHazardousMaterialUnitedNationsClassificationCode_QNAME = new QName("", "NationalHazardousMaterialUnitedNationsClassificationCode");
    private final static QName _ProprietaryLocationIdentifier_QNAME = new QName("", "ProprietaryLocationIdentifier");
    private final static QName _DateTimeStamp_QNAME = new QName("", "DateTimeStamp");
    private final static QName _AffirmationIndicator_QNAME = new QName("", "AffirmationIndicator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.e2open.transform
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShippingContainer }
     * 
     */
    public ShippingContainer createShippingContainer() {
        return new ShippingContainer();
    }

    /**
     * Create an instance of {@link LinearPhysicalDimension }
     * 
     */
    public LinearPhysicalDimension createLinearPhysicalDimension() {
        return new LinearPhysicalDimension();
    }

    /**
     * Create an instance of {@link MassPhysicalDimension }
     * 
     */
    public MassPhysicalDimension createMassPhysicalDimension() {
        return new MassPhysicalDimension();
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link NumberOfShippingContainers }
     * 
     */
    public NumberOfShippingContainers createNumberOfShippingContainers() {
        return new NumberOfShippingContainers();
    }

    /**
     * Create an instance of {@link ShippingContainerIdentifier }
     * 
     */
    public ShippingContainerIdentifier createShippingContainerIdentifier() {
        return new ShippingContainerIdentifier();
    }

    /**
     * Create an instance of {@link ShippingContainerItem }
     * 
     */
    public ShippingContainerItem createShippingContainerItem() {
        return new ShippingContainerItem();
    }

    /**
     * Create an instance of {@link DocumentSubLineLotShipReference }
     * 
     */
    public DocumentSubLineLotShipReference createDocumentSubLineLotShipReference() {
        return new DocumentSubLineLotShipReference();
    }

    /**
     * Create an instance of {@link LotShipReference }
     * 
     */
    public LotShipReference createLotShipReference() {
        return new LotShipReference();
    }

    /**
     * Create an instance of {@link ExpiryDate }
     * 
     */
    public ExpiryDate createExpiryDate() {
        return new ExpiryDate();
    }

    /**
     * Create an instance of {@link LotIdentification }
     * 
     */
    public LotIdentification createLotIdentification() {
        return new LotIdentification();
    }

    /**
     * Create an instance of {@link PrimaryLotIdentifier }
     * 
     */
    public PrimaryLotIdentifier createPrimaryLotIdentifier() {
        return new PrimaryLotIdentifier();
    }

    /**
     * Create an instance of {@link SecondaryLotIdentifier }
     * 
     */
    public SecondaryLotIdentifier createSecondaryLotIdentifier() {
        return new SecondaryLotIdentifier();
    }

    /**
     * Create an instance of {@link LotQuantity }
     * 
     */
    public LotQuantity createLotQuantity() {
        return new LotQuantity();
    }

    /**
     * Create an instance of {@link ManufacturingDateCode }
     * 
     */
    public ManufacturingDateCode createManufacturingDateCode() {
        return new ManufacturingDateCode();
    }

    /**
     * Create an instance of {@link RequestedQuantity }
     * 
     */
    public RequestedQuantity createRequestedQuantity() {
        return new RequestedQuantity();
    }

    /**
     * Create an instance of {@link ShippedLotQuantity }
     * 
     */
    public ShippedLotQuantity createShippedLotQuantity() {
        return new ShippedLotQuantity();
    }

    /**
     * Create an instance of {@link SubLineNumber }
     * 
     */
    public SubLineNumber createSubLineNumber() {
        return new SubLineNumber();
    }

    /**
     * Create an instance of {@link ExportLicense }
     * 
     */
    public ExportLicense createExportLicense() {
        return new ExportLicense();
    }

    /**
     * Create an instance of {@link HazardousMaterialDescription }
     * 
     */
    public HazardousMaterialDescription createHazardousMaterialDescription() {
        return new HazardousMaterialDescription();
    }

    /**
     * Create an instance of {@link IsContainsHazardousMaterial }
     * 
     */
    public IsContainsHazardousMaterial createIsContainsHazardousMaterial() {
        return new IsContainsHazardousMaterial();
    }

    /**
     * Create an instance of {@link ManufacturerProfile }
     * 
     */
    public ManufacturerProfile createManufacturerProfile() {
        return new ManufacturerProfile();
    }

    /**
     * Create an instance of {@link CountryOfOrigin }
     * 
     */
    public CountryOfOrigin createCountryOfOrigin() {
        return new CountryOfOrigin();
    }

    /**
     * Create an instance of {@link ManufactureDate }
     * 
     */
    public ManufactureDate createManufactureDate() {
        return new ManufactureDate();
    }

    /**
     * Create an instance of {@link ProductSerialIdentifier }
     * 
     */
    public ProductSerialIdentifier createProductSerialIdentifier() {
        return new ProductSerialIdentifier();
    }

    /**
     * Create an instance of {@link NumberOfItemPackages }
     * 
     */
    public NumberOfItemPackages createNumberOfItemPackages() {
        return new NumberOfItemPackages();
    }

    /**
     * Create an instance of {@link ProductIdentification }
     * 
     */
    public ProductIdentification createProductIdentification() {
        return new ProductIdentification();
    }

    /**
     * Create an instance of {@link PartnerProductIdentification }
     * 
     */
    public PartnerProductIdentification createPartnerProductIdentification() {
        return new PartnerProductIdentification();
    }

    /**
     * Create an instance of {@link RevisionIdentifier }
     * 
     */
    public RevisionIdentifier createRevisionIdentifier() {
        return new RevisionIdentifier();
    }

    /**
     * Create an instance of {@link FreeFormText }
     * 
     */
    public FreeFormText createFreeFormText() {
        return new FreeFormText();
    }

    /**
     * Create an instance of {@link ShippedQuantity }
     * 
     */
    public ShippedQuantity createShippedQuantity() {
        return new ShippedQuantity();
    }

    /**
     * Create an instance of {@link ShippingContainerItemIdentifier }
     * 
     */
    public ShippingContainerItemIdentifier createShippingContainerItemIdentifier() {
        return new ShippingContainerItemIdentifier();
    }

    /**
     * Create an instance of {@link TraceIdentifier }
     * 
     */
    public TraceIdentifier createTraceIdentifier() {
        return new TraceIdentifier();
    }

    /**
     * Create an instance of {@link SubContainer }
     * 
     */
    public SubContainer createSubContainer() {
        return new SubContainer();
    }

    /**
     * Create an instance of {@link TrackingReference }
     * 
     */
    public TrackingReference createTrackingReference() {
        return new TrackingReference();
    }

    /**
     * Create an instance of {@link AdvancedShipmentNotification }
     * 
     */
    public AdvancedShipmentNotification createAdvancedShipmentNotification() {
        return new AdvancedShipmentNotification();
    }

    /**
     * Create an instance of {@link BuyingPartner }
     * 
     */
    public BuyingPartner createBuyingPartner() {
        return new BuyingPartner();
    }

    /**
     * Create an instance of {@link PurchasedBy }
     * 
     */
    public PurchasedBy createPurchasedBy() {
        return new PurchasedBy();
    }

    /**
     * Create an instance of {@link PartnerDescription }
     * 
     */
    public PartnerDescription createPartnerDescription() {
        return new PartnerDescription();
    }

    /**
     * Create an instance of {@link BusinessDescription }
     * 
     */
    public BusinessDescription createBusinessDescription() {
        return new BusinessDescription();
    }

    /**
     * Create an instance of {@link BusinessName }
     * 
     */
    public BusinessName createBusinessName() {
        return new BusinessName();
    }

    /**
     * Create an instance of {@link PartnerBusinessIdentification }
     * 
     */
    public PartnerBusinessIdentification createPartnerBusinessIdentification() {
        return new PartnerBusinessIdentification();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link ContactName }
     * 
     */
    public ContactName createContactName() {
        return new ContactName();
    }

    /**
     * Create an instance of {@link FacsimileNumber }
     * 
     */
    public FacsimileNumber createFacsimileNumber() {
        return new FacsimileNumber();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link PhysicalLocation }
     * 
     */
    public PhysicalLocation createPhysicalLocation() {
        return new PhysicalLocation();
    }

    /**
     * Create an instance of {@link PartnerLocationIdentification }
     * 
     */
    public PartnerLocationIdentification createPartnerLocationIdentification() {
        return new PartnerLocationIdentification();
    }

    /**
     * Create an instance of {@link PhysicalAddress }
     * 
     */
    public PhysicalAddress createPhysicalAddress() {
        return new PhysicalAddress();
    }

    /**
     * Create an instance of {@link AddressLine1 }
     * 
     */
    public AddressLine1 createAddressLine1() {
        return new AddressLine1();
    }

    /**
     * Create an instance of {@link AddressLine2 }
     * 
     */
    public AddressLine2 createAddressLine2() {
        return new AddressLine2();
    }

    /**
     * Create an instance of {@link AddressLine3 }
     * 
     */
    public AddressLine3 createAddressLine3() {
        return new AddressLine3();
    }

    /**
     * Create an instance of {@link CityName }
     * 
     */
    public CityName createCityName() {
        return new CityName();
    }

    /**
     * Create an instance of {@link PostOfficeBoxIdentifier }
     * 
     */
    public PostOfficeBoxIdentifier createPostOfficeBoxIdentifier() {
        return new PostOfficeBoxIdentifier();
    }

    /**
     * Create an instance of {@link RegionName }
     * 
     */
    public RegionName createRegionName() {
        return new RegionName();
    }

    /**
     * Create an instance of {@link OriginatingPartner }
     * 
     */
    public OriginatingPartner createOriginatingPartner() {
        return new OriginatingPartner();
    }

    /**
     * Create an instance of {@link ShipFrom }
     * 
     */
    public ShipFrom createShipFrom() {
        return new ShipFrom();
    }

    /**
     * Create an instance of {@link SellingPartner }
     * 
     */
    public SellingPartner createSellingPartner() {
        return new SellingPartner();
    }

    /**
     * Create an instance of {@link SoldBy }
     * 
     */
    public SoldBy createSoldBy() {
        return new SoldBy();
    }

    /**
     * Create an instance of {@link Shipment }
     * 
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link FreightPaymentAccount }
     * 
     */
    public FreightPaymentAccount createFreightPaymentAccount() {
        return new FreightPaymentAccount();
    }

    /**
     * Create an instance of {@link ReceivingPartner }
     * 
     */
    public ReceivingPartner createReceivingPartner() {
        return new ReceivingPartner();
    }

    /**
     * Create an instance of {@link ShipTo }
     * 
     */
    public ShipTo createShipTo() {
        return new ShipTo();
    }

    /**
     * Create an instance of {@link ShipmentChangeReason }
     * 
     */
    public ShipmentChangeReason createShipmentChangeReason() {
        return new ShipmentChangeReason();
    }

    /**
     * Create an instance of {@link ShipmentIdentifier }
     * 
     */
    public ShipmentIdentifier createShipmentIdentifier() {
        return new ShipmentIdentifier();
    }

    /**
     * Create an instance of {@link ShipmentTransportationEvent }
     * 
     */
    public ShipmentTransportationEvent createShipmentTransportationEvent() {
        return new ShipmentTransportationEvent();
    }

    /**
     * Create an instance of {@link TransportedBy }
     * 
     */
    public TransportedBy createTransportedBy() {
        return new TransportedBy();
    }

    /**
     * Create an instance of {@link ThisDocumentIdentifier }
     * 
     */
    public ThisDocumentIdentifier createThisDocumentIdentifier() {
        return new ThisDocumentIdentifier();
    }

    /**
     * Create an instance of {@link FromRole }
     * 
     */
    public FromRole createFromRole() {
        return new FromRole();
    }

    /**
     * Create an instance of {@link PartnerRoleDescription }
     * 
     */
    public PartnerRoleDescription createPartnerRoleDescription() {
        return new PartnerRoleDescription();
    }

    /**
     * Create an instance of {@link ToRole }
     * 
     */
    public ToRole createToRole() {
        return new ToRole();
    }

    /**
     * Create an instance of {@link ThisDocumentGenerationDateTime }
     * 
     */
    public ThisDocumentGenerationDateTime createThisDocumentGenerationDateTime() {
        return new ThisDocumentGenerationDateTime();
    }

    /**
     * Create an instance of {@link Pip3B2AdvanceShipmentNotification }
     * 
     */
    public Pip3B2AdvanceShipmentNotification createPip3B2AdvanceShipmentNotification() {
        return new Pip3B2AdvanceShipmentNotification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProductQuantity")
    public JAXBElement<String> createProductQuantity(String value) {
        return new JAXBElement<String>(_ProductQuantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NationalHarmonizedTariffScheduleCode")
    public JAXBElement<String> createNationalHarmonizedTariffScheduleCode(String value) {
        return new JAXBElement<String>(_NationalHarmonizedTariffScheduleCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalTrackingReferenceTypeCode")
    public JAXBElement<String> createGlobalTrackingReferenceTypeCode(String value) {
        return new JAXBElement<String>(_GlobalTrackingReferenceTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryBusinessIdentifier")
    public JAXBElement<String> createProprietaryBusinessIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryBusinessIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WidthDimension")
    public JAXBElement<String> createWidthDimension(String value) {
        return new JAXBElement<String>(_WidthDimension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalCountryCode")
    public JAXBElement<String> createGlobalCountryCode(String value) {
        return new JAXBElement<String>(_GlobalCountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryReferenceIdentifier")
    public JAXBElement<String> createProprietaryReferenceIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryReferenceIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryDocumentIdentifier")
    public JAXBElement<String> createProprietaryDocumentIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryDocumentIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LengthDimension")
    public JAXBElement<String> createLengthDimension(String value) {
        return new JAXBElement<String>(_LengthDimension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineNumber")
    public JAXBElement<String> createLineNumber(String value) {
        return new JAXBElement<String>(_LineNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CommunicationsNumber")
    public JAXBElement<String> createCommunicationsNumber(String value) {
        return new JAXBElement<String>(_CommunicationsNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietarySerialIdentifier")
    public JAXBElement<String> createProprietarySerialIdentifier(String value) {
        return new JAXBElement<String>(_ProprietarySerialIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryLotIdentifier")
    public JAXBElement<String> createProprietaryLotIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryLotIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryDomainIdentifier")
    public JAXBElement<String> createProprietaryDomainIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryDomainIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NationalPostalCode")
    public JAXBElement<String> createNationalPostalCode(String value) {
        return new JAXBElement<String>(_NationalPostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalLotQuantityClassificationCode")
    public JAXBElement<String> createGlobalLotQuantityClassificationCode(String value) {
        return new JAXBElement<String>(_GlobalLotQuantityClassificationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalBusinessIdentifier")
    public JAXBElement<String> createGlobalBusinessIdentifier(String value) {
        return new JAXBElement<String>(_GlobalBusinessIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalShippingServiceLevelCode")
    public JAXBElement<String> createGlobalShippingServiceLevelCode(String value) {
        return new JAXBElement<String>(_GlobalShippingServiceLevelCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HeightDimension")
    public JAXBElement<String> createHeightDimension(String value) {
        return new JAXBElement<String>(_HeightDimension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalPartnerClassificationCode")
    public JAXBElement<String> createGlobalPartnerClassificationCode(String value) {
        return new JAXBElement<String>(_GlobalPartnerClassificationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalSupplyChainCode")
    public JAXBElement<String> createGlobalSupplyChainCode(String value) {
        return new JAXBElement<String>(_GlobalSupplyChainCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalShipDateCode")
    public JAXBElement<String> createGlobalShipDateCode(String value) {
        return new JAXBElement<String>(_GlobalShipDateCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalProductIdentifier")
    public JAXBElement<String> createGlobalProductIdentifier(String value) {
        return new JAXBElement<String>(_GlobalProductIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalDocumentReferenceTypeCode")
    public JAXBElement<String> createGlobalDocumentReferenceTypeCode(String value) {
        return new JAXBElement<String>(_GlobalDocumentReferenceTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryIdentifierAuthority")
    public JAXBElement<String> createProprietaryIdentifierAuthority(String value) {
        return new JAXBElement<String>(_ProprietaryIdentifierAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalPartnerRoleClassificationCode")
    public JAXBElement<String> createGlobalPartnerRoleClassificationCode(String value) {
        return new JAXBElement<String>(_GlobalPartnerRoleClassificationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalLocationIdentifier")
    public JAXBElement<String> createGlobalLocationIdentifier(String value) {
        return new JAXBElement<String>(_GlobalLocationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalShipmentChangeDispositionCode")
    public JAXBElement<String> createGlobalShipmentChangeDispositionCode(String value) {
        return new JAXBElement<String>(_GlobalShipmentChangeDispositionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalPhysicalUnitOfMeasureCode")
    public JAXBElement<String> createGlobalPhysicalUnitOfMeasureCode(String value) {
        return new JAXBElement<String>(_GlobalPhysicalUnitOfMeasureCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NationalExportControlClassificationCode")
    public JAXBElement<String> createNationalExportControlClassificationCode(String value) {
        return new JAXBElement<String>(_NationalExportControlClassificationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalPackageTypeCode")
    public JAXBElement<String> createGlobalPackageTypeCode(String value) {
        return new JAXBElement<String>(_GlobalPackageTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateStamp")
    public JAXBElement<String> createDateStamp(String value) {
        return new JAXBElement<String>(_DateStamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalCarrierCode")
    public JAXBElement<String> createGlobalCarrierCode(String value) {
        return new JAXBElement<String>(_GlobalCarrierCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountableAmount")
    public JAXBElement<String> createCountableAmount(String value) {
        return new JAXBElement<String>(_CountableAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryShipmentTrackingIdentifier")
    public JAXBElement<String> createProprietaryShipmentTrackingIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryShipmentTrackingIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailAddress")
    public JAXBElement<String> createEmailAddress(String value) {
        return new JAXBElement<String>(_EmailAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalIncotermsCode")
    public JAXBElement<String> createGlobalIncotermsCode(String value) {
        return new JAXBElement<String>(_GlobalIncotermsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccountNumber")
    public JAXBElement<String> createAccountNumber(String value) {
        return new JAXBElement<String>(_AccountNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Mass")
    public JAXBElement<String> createMass(String value) {
        return new JAXBElement<String>(_Mass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryProductIdentifier")
    public JAXBElement<String> createProprietaryProductIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryProductIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalShipmentModeCode")
    public JAXBElement<String> createGlobalShipmentModeCode(String value) {
        return new JAXBElement<String>(_GlobalShipmentModeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalDocumentFunctionCode")
    public JAXBElement<String> createGlobalDocumentFunctionCode(String value) {
        return new JAXBElement<String>(_GlobalDocumentFunctionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalProductUnitOfMeasureCode")
    public JAXBElement<String> createGlobalProductUnitOfMeasureCode(String value) {
        return new JAXBElement<String>(_GlobalProductUnitOfMeasureCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NationalHazardousMaterialUnitedNationsClassificationCode")
    public JAXBElement<String> createNationalHazardousMaterialUnitedNationsClassificationCode(String value) {
        return new JAXBElement<String>(_NationalHazardousMaterialUnitedNationsClassificationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProprietaryLocationIdentifier")
    public JAXBElement<String> createProprietaryLocationIdentifier(String value) {
        return new JAXBElement<String>(_ProprietaryLocationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateTimeStamp")
    public JAXBElement<String> createDateTimeStamp(String value) {
        return new JAXBElement<String>(_DateTimeStamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AffirmationIndicator")
    public JAXBElement<String> createAffirmationIndicator(String value) {
        return new JAXBElement<String>(_AffirmationIndicator_QNAME, String.class, null, value);
    }

}
