//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BusinessDescription"/>
 *         &lt;element ref="{}ContactInformation" minOccurs="0"/>
 *         &lt;element ref="{}GlobalPartnerClassificationCode"/>
 *         &lt;element ref="{}PhysicalLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "businessDescription",
    "contactInformation",
    "globalPartnerClassificationCode",
    "physicalLocation"
})
@XmlRootElement(name = "PartnerDescription")
public class PartnerDescription {

    @XmlElement(name = "BusinessDescription", required = true)
    protected BusinessDescription businessDescription;
    @XmlElement(name = "ContactInformation")
    protected ContactInformation contactInformation;
    @XmlElement(name = "GlobalPartnerClassificationCode", required = true)
    protected String globalPartnerClassificationCode;
    @XmlElement(name = "PhysicalLocation")
    protected PhysicalLocation physicalLocation;

    /**
     * Gets the value of the businessDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDescription }
     *     
     */
    public BusinessDescription getBusinessDescription() {
        return businessDescription;
    }

    /**
     * Sets the value of the businessDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDescription }
     *     
     */
    public void setBusinessDescription(BusinessDescription value) {
        this.businessDescription = value;
    }

    /**
     * Gets the value of the contactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInformation }
     *     
     */
    public ContactInformation getContactInformation() {
        return contactInformation;
    }

    /**
     * Sets the value of the contactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInformation }
     *     
     */
    public void setContactInformation(ContactInformation value) {
        this.contactInformation = value;
    }

    /**
     * Gets the value of the globalPartnerClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalPartnerClassificationCode() {
        return globalPartnerClassificationCode;
    }

    /**
     * Sets the value of the globalPartnerClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalPartnerClassificationCode(String value) {
        this.globalPartnerClassificationCode = value;
    }

    /**
     * Gets the value of the physicalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalLocation }
     *     
     */
    public PhysicalLocation getPhysicalLocation() {
        return physicalLocation;
    }

    /**
     * Sets the value of the physicalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalLocation }
     *     
     */
    public void setPhysicalLocation(PhysicalLocation value) {
        this.physicalLocation = value;
    }

}
