//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GlobalPartnerClassificationCode"/>
 *         &lt;element ref="{}ProprietaryProductIdentifier"/>
 *         &lt;element ref="{}revisionIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalPartnerClassificationCode",
    "proprietaryProductIdentifier",
    "revisionIdentifier"
})
@XmlRootElement(name = "PartnerProductIdentification")
public class PartnerProductIdentification {

    @XmlElement(name = "GlobalPartnerClassificationCode", required = true)
    protected String globalPartnerClassificationCode;
    @XmlElement(name = "ProprietaryProductIdentifier", required = true)
    protected String proprietaryProductIdentifier;
    protected RevisionIdentifier revisionIdentifier;

    /**
     * Gets the value of the globalPartnerClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalPartnerClassificationCode() {
        return globalPartnerClassificationCode;
    }

    /**
     * Sets the value of the globalPartnerClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalPartnerClassificationCode(String value) {
        this.globalPartnerClassificationCode = value;
    }

    /**
     * Gets the value of the proprietaryProductIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProprietaryProductIdentifier() {
        return proprietaryProductIdentifier;
    }

    /**
     * Sets the value of the proprietaryProductIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProprietaryProductIdentifier(String value) {
        this.proprietaryProductIdentifier = value;
    }

    /**
     * Gets the value of the revisionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionIdentifier }
     *     
     */
    public RevisionIdentifier getRevisionIdentifier() {
        return revisionIdentifier;
    }

    /**
     * Sets the value of the revisionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionIdentifier }
     *     
     */
    public void setRevisionIdentifier(RevisionIdentifier value) {
        this.revisionIdentifier = value;
    }

}
