//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}addressLine1" minOccurs="0"/>
 *         &lt;element ref="{}addressLine2" minOccurs="0"/>
 *         &lt;element ref="{}addressLine3" minOccurs="0"/>
 *         &lt;element ref="{}cityName" minOccurs="0"/>
 *         &lt;element ref="{}GlobalCountryCode" minOccurs="0"/>
 *         &lt;element ref="{}NationalPostalCode" minOccurs="0"/>
 *         &lt;element ref="{}postOfficeBoxIdentifier" minOccurs="0"/>
 *         &lt;element ref="{}regionName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressLine1",
    "addressLine2",
    "addressLine3",
    "cityName",
    "globalCountryCode",
    "nationalPostalCode",
    "postOfficeBoxIdentifier",
    "regionName"
})
@XmlRootElement(name = "PhysicalAddress")
public class PhysicalAddress {

    protected AddressLine1 addressLine1;
    protected AddressLine2 addressLine2;
    protected AddressLine3 addressLine3;
    protected CityName cityName;
    @XmlElement(name = "GlobalCountryCode")
    protected String globalCountryCode;
    @XmlElement(name = "NationalPostalCode")
    protected String nationalPostalCode;
    protected PostOfficeBoxIdentifier postOfficeBoxIdentifier;
    protected RegionName regionName;

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link AddressLine1 }
     *     
     */
    public AddressLine1 getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressLine1 }
     *     
     */
    public void setAddressLine1(AddressLine1 value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link AddressLine2 }
     *     
     */
    public AddressLine2 getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressLine2 }
     *     
     */
    public void setAddressLine2(AddressLine2 value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the addressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link AddressLine3 }
     *     
     */
    public AddressLine3 getAddressLine3() {
        return addressLine3;
    }

    /**
     * Sets the value of the addressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressLine3 }
     *     
     */
    public void setAddressLine3(AddressLine3 value) {
        this.addressLine3 = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible object is
     *     {@link CityName }
     *     
     */
    public CityName getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityName }
     *     
     */
    public void setCityName(CityName value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the globalCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalCountryCode() {
        return globalCountryCode;
    }

    /**
     * Sets the value of the globalCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalCountryCode(String value) {
        this.globalCountryCode = value;
    }

    /**
     * Gets the value of the nationalPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalPostalCode() {
        return nationalPostalCode;
    }

    /**
     * Sets the value of the nationalPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalPostalCode(String value) {
        this.nationalPostalCode = value;
    }

    /**
     * Gets the value of the postOfficeBoxIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PostOfficeBoxIdentifier }
     *     
     */
    public PostOfficeBoxIdentifier getPostOfficeBoxIdentifier() {
        return postOfficeBoxIdentifier;
    }

    /**
     * Sets the value of the postOfficeBoxIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostOfficeBoxIdentifier }
     *     
     */
    public void setPostOfficeBoxIdentifier(PostOfficeBoxIdentifier value) {
        this.postOfficeBoxIdentifier = value;
    }

    /**
     * Gets the value of the regionName property.
     * 
     * @return
     *     possible object is
     *     {@link RegionName }
     *     
     */
    public RegionName getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionName }
     *     
     */
    public void setRegionName(RegionName value) {
        this.regionName = value;
    }

}
