//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AdvancedShipmentNotification"/>
 *         &lt;element ref="{}fromRole"/>
 *         &lt;element ref="{}GlobalDocumentFunctionCode"/>
 *         &lt;element ref="{}thisDocumentGenerationDateTime"/>
 *         &lt;element ref="{}thisDocumentIdentifier"/>
 *         &lt;element ref="{}toRole"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "advancedShipmentNotification",
    "fromRole",
    "globalDocumentFunctionCode",
    "thisDocumentGenerationDateTime",
    "thisDocumentIdentifier",
    "toRole"
})
@XmlRootElement(name = "Pip3B2AdvanceShipmentNotification")
public class Pip3B2AdvanceShipmentNotification {

    @XmlElement(name = "AdvancedShipmentNotification", required = true)
    protected AdvancedShipmentNotification advancedShipmentNotification;
    @XmlElement(required = true)
    protected FromRole fromRole;
    @XmlElement(name = "GlobalDocumentFunctionCode", required = true)
    protected String globalDocumentFunctionCode;
    @XmlElement(required = true)
    protected ThisDocumentGenerationDateTime thisDocumentGenerationDateTime;
    @XmlElement(required = true)
    protected ThisDocumentIdentifier thisDocumentIdentifier;
    @XmlElement(required = true)
    protected ToRole toRole;

    /**
     * Gets the value of the advancedShipmentNotification property.
     * 
     * @return
     *     possible object is
     *     {@link AdvancedShipmentNotification }
     *     
     */
    public AdvancedShipmentNotification getAdvancedShipmentNotification() {
        return advancedShipmentNotification;
    }

    /**
     * Sets the value of the advancedShipmentNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvancedShipmentNotification }
     *     
     */
    public void setAdvancedShipmentNotification(AdvancedShipmentNotification value) {
        this.advancedShipmentNotification = value;
    }

    /**
     * Gets the value of the fromRole property.
     * 
     * @return
     *     possible object is
     *     {@link FromRole }
     *     
     */
    public FromRole getFromRole() {
        return fromRole;
    }

    /**
     * Sets the value of the fromRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromRole }
     *     
     */
    public void setFromRole(FromRole value) {
        this.fromRole = value;
    }

    /**
     * Gets the value of the globalDocumentFunctionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalDocumentFunctionCode() {
        return globalDocumentFunctionCode;
    }

    /**
     * Sets the value of the globalDocumentFunctionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalDocumentFunctionCode(String value) {
        this.globalDocumentFunctionCode = value;
    }

    /**
     * Gets the value of the thisDocumentGenerationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link ThisDocumentGenerationDateTime }
     *     
     */
    public ThisDocumentGenerationDateTime getThisDocumentGenerationDateTime() {
        return thisDocumentGenerationDateTime;
    }

    /**
     * Sets the value of the thisDocumentGenerationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThisDocumentGenerationDateTime }
     *     
     */
    public void setThisDocumentGenerationDateTime(ThisDocumentGenerationDateTime value) {
        this.thisDocumentGenerationDateTime = value;
    }

    /**
     * Gets the value of the thisDocumentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ThisDocumentIdentifier }
     *     
     */
    public ThisDocumentIdentifier getThisDocumentIdentifier() {
        return thisDocumentIdentifier;
    }

    /**
     * Sets the value of the thisDocumentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThisDocumentIdentifier }
     *     
     */
    public void setThisDocumentIdentifier(ThisDocumentIdentifier value) {
        this.thisDocumentIdentifier = value;
    }

    /**
     * Gets the value of the toRole property.
     * 
     * @return
     *     possible object is
     *     {@link ToRole }
     *     
     */
    public ToRole getToRole() {
        return toRole;
    }

    /**
     * Sets the value of the toRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToRole }
     *     
     */
    public void setToRole(ToRole value) {
        this.toRole = value;
    }

}
