//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 04:49:09 PM SGT 
//


package com.e2open.transform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DocumentSubLineLotShipReference" maxOccurs="unbounded"/>
 *         &lt;element ref="{}ExportLicense" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}GlobalProductUnitOfMeasureCode"/>
 *         &lt;element ref="{}HazardousMaterialDescription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}isContainsHazardousMaterial"/>
 *         &lt;element ref="{}ManufacturerProfile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}NationalHarmonizedTariffScheduleCode" minOccurs="0"/>
 *         &lt;element ref="{}numberOfItemPackages" minOccurs="0"/>
 *         &lt;element ref="{}ProductIdentification"/>
 *         &lt;element ref="{}shippedQuantity"/>
 *         &lt;element ref="{}shippingContainerItemIdentifier" minOccurs="0"/>
 *         &lt;element ref="{}traceIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentSubLineLotShipReference",
    "exportLicense",
    "globalProductUnitOfMeasureCode",
    "hazardousMaterialDescription",
    "isContainsHazardousMaterial",
    "manufacturerProfile",
    "nationalHarmonizedTariffScheduleCode",
    "numberOfItemPackages",
    "productIdentification",
    "shippedQuantity",
    "shippingContainerItemIdentifier",
    "traceIdentifier"
})
@XmlRootElement(name = "ShippingContainerItem")
public class ShippingContainerItem {

    @XmlElement(name = "DocumentSubLineLotShipReference", required = true)
    protected List<DocumentSubLineLotShipReference> documentSubLineLotShipReference;
    @XmlElement(name = "ExportLicense")
    protected List<ExportLicense> exportLicense;
    @XmlElement(name = "GlobalProductUnitOfMeasureCode", required = true)
    protected String globalProductUnitOfMeasureCode;
    @XmlElement(name = "HazardousMaterialDescription")
    protected List<HazardousMaterialDescription> hazardousMaterialDescription;
    @XmlElement(required = true)
    protected IsContainsHazardousMaterial isContainsHazardousMaterial;
    @XmlElement(name = "ManufacturerProfile")
    protected List<ManufacturerProfile> manufacturerProfile;
    @XmlElement(name = "NationalHarmonizedTariffScheduleCode")
    protected String nationalHarmonizedTariffScheduleCode;
    protected NumberOfItemPackages numberOfItemPackages;
    @XmlElement(name = "ProductIdentification", required = true)
    protected ProductIdentification productIdentification;
    @XmlElement(required = true)
    protected ShippedQuantity shippedQuantity;
    protected ShippingContainerItemIdentifier shippingContainerItemIdentifier;
    protected List<TraceIdentifier> traceIdentifier;

    /**
     * Gets the value of the documentSubLineLotShipReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSubLineLotShipReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSubLineLotShipReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentSubLineLotShipReference }
     * 
     * 
     */
    public List<DocumentSubLineLotShipReference> getDocumentSubLineLotShipReference() {
        if (documentSubLineLotShipReference == null) {
            documentSubLineLotShipReference = new ArrayList<DocumentSubLineLotShipReference>();
        }
        return this.documentSubLineLotShipReference;
    }

    /**
     * Gets the value of the exportLicense property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exportLicense property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExportLicense().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExportLicense }
     * 
     * 
     */
    public List<ExportLicense> getExportLicense() {
        if (exportLicense == null) {
            exportLicense = new ArrayList<ExportLicense>();
        }
        return this.exportLicense;
    }

    /**
     * Gets the value of the globalProductUnitOfMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalProductUnitOfMeasureCode() {
        return globalProductUnitOfMeasureCode;
    }

    /**
     * Sets the value of the globalProductUnitOfMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalProductUnitOfMeasureCode(String value) {
        this.globalProductUnitOfMeasureCode = value;
    }

    /**
     * Gets the value of the hazardousMaterialDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hazardousMaterialDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHazardousMaterialDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HazardousMaterialDescription }
     * 
     * 
     */
    public List<HazardousMaterialDescription> getHazardousMaterialDescription() {
        if (hazardousMaterialDescription == null) {
            hazardousMaterialDescription = new ArrayList<HazardousMaterialDescription>();
        }
        return this.hazardousMaterialDescription;
    }

    /**
     * Gets the value of the isContainsHazardousMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link IsContainsHazardousMaterial }
     *     
     */
    public IsContainsHazardousMaterial getIsContainsHazardousMaterial() {
        return isContainsHazardousMaterial;
    }

    /**
     * Sets the value of the isContainsHazardousMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsContainsHazardousMaterial }
     *     
     */
    public void setIsContainsHazardousMaterial(IsContainsHazardousMaterial value) {
        this.isContainsHazardousMaterial = value;
    }

    /**
     * Gets the value of the manufacturerProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manufacturerProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManufacturerProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerProfile }
     * 
     * 
     */
    public List<ManufacturerProfile> getManufacturerProfile() {
        if (manufacturerProfile == null) {
            manufacturerProfile = new ArrayList<ManufacturerProfile>();
        }
        return this.manufacturerProfile;
    }

    /**
     * Gets the value of the nationalHarmonizedTariffScheduleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalHarmonizedTariffScheduleCode() {
        return nationalHarmonizedTariffScheduleCode;
    }

    /**
     * Sets the value of the nationalHarmonizedTariffScheduleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalHarmonizedTariffScheduleCode(String value) {
        this.nationalHarmonizedTariffScheduleCode = value;
    }

    /**
     * Gets the value of the numberOfItemPackages property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfItemPackages }
     *     
     */
    public NumberOfItemPackages getNumberOfItemPackages() {
        return numberOfItemPackages;
    }

    /**
     * Sets the value of the numberOfItemPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfItemPackages }
     *     
     */
    public void setNumberOfItemPackages(NumberOfItemPackages value) {
        this.numberOfItemPackages = value;
    }

    /**
     * Gets the value of the productIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ProductIdentification }
     *     
     */
    public ProductIdentification getProductIdentification() {
        return productIdentification;
    }

    /**
     * Sets the value of the productIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductIdentification }
     *     
     */
    public void setProductIdentification(ProductIdentification value) {
        this.productIdentification = value;
    }

    /**
     * Gets the value of the shippedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link ShippedQuantity }
     *     
     */
    public ShippedQuantity getShippedQuantity() {
        return shippedQuantity;
    }

    /**
     * Sets the value of the shippedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippedQuantity }
     *     
     */
    public void setShippedQuantity(ShippedQuantity value) {
        this.shippedQuantity = value;
    }

    /**
     * Gets the value of the shippingContainerItemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingContainerItemIdentifier }
     *     
     */
    public ShippingContainerItemIdentifier getShippingContainerItemIdentifier() {
        return shippingContainerItemIdentifier;
    }

    /**
     * Sets the value of the shippingContainerItemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingContainerItemIdentifier }
     *     
     */
    public void setShippingContainerItemIdentifier(ShippingContainerItemIdentifier value) {
        this.shippingContainerItemIdentifier = value;
    }

    /**
     * Gets the value of the traceIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traceIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraceIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TraceIdentifier }
     * 
     * 
     */
    public List<TraceIdentifier> getTraceIdentifier() {
        if (traceIdentifier == null) {
            traceIdentifier = new ArrayList<TraceIdentifier>();
        }
        return this.traceIdentifier;
    }

}
